import test from 'node:test';
import assert from 'node:assert/strict';
import {settleLaunchAlliance,publicAllianceSettlement} from '../src/lib/launchAllianceSettlement.js';
function fixture(){let record={},prepares=0,sends=0;const calls=[];return {calls,get record(){return record;},get prepares(){return prepares;},get sends(){return sends;},load:async()=>record,save:async state=>{calls.push('save');record=structuredClone(state);},prepare:async()=>{prepares++;return {signature:'signed-1',rawBase64:Buffer.from('signed bytes').toString('base64'),blockhash:'block',lastValidBlockHeight:100};},connection:{sendRawTransaction:async()=>{sends++;calls.push('send');return 'signed-1';},confirmTransaction:async()=>({value:{err:null}}),getSignatureStatus:async()=>({value:{confirmationStatus:'confirmed'}}),getBlockHeight:async()=>101},now:()=> '2026-09-27T12:00:00.000Z'};}
test('Alliance records signed intent before broadcast and only then confirms a receipt',async()=>{const f=fixture();const r=await settleLaunchAlliance(f);assert.equal(r.status,'CONFIRMED');assert.deepEqual(f.calls.slice(0,2),['save','send']);assert.equal(r.receipts.length,1);assert.equal(r.pending,null);assert.equal(publicAllianceSettlement(r).rawBase64,undefined);});
test('failed persistence prevents any broadcast',async()=>{const f=fixture();f.save=async()=>{throw new Error('disk full');};await assert.rejects(settleLaunchAlliance(f),/disk full/);assert.equal(f.sends,0);});

test('receipt persistence failure retains the signed intent for reconciliation',async()=>{const f=fixture();const save=f.save;let failed=false;f.save=async state=>{if(state.status==='CONFIRMED'&&!failed){failed=true;throw new Error('receipt write failed');}await save(state);};const first=await settleLaunchAlliance(f);assert.equal(first.pending.signature,'signed-1');const second=await settleLaunchAlliance(f);assert.equal(second.status,'CONFIRMED');assert.equal(f.sends,1);assert.equal(f.prepares,1);assert.equal(second.receipts.length,1);});
test('unknown broadcasts are reconciled rather than rebuilt after restart',async()=>{const f=fixture();f.connection.sendRawTransaction=async()=>{throw new Error('timeout');};const first=await settleLaunchAlliance(f);assert.equal(first.status,'PENDING');f.connection.getSignatureStatus=async()=>{throw new Error('RPC unavailable');};const second=await settleLaunchAlliance(f);assert.equal(second.status,'PENDING');assert.equal(f.prepares,1);f.connection.getSignatureStatus=async()=>({value:{confirmationStatus:'confirmed'}});const final=await settleLaunchAlliance(f);assert.equal(final.status,'CONFIRMED');assert.equal(f.prepares,1);assert.equal(final.receipts.length,1);});
test('expiry requires finalized height and a second absent signature lookup',async()=>{const f=fixture();f.connection.sendRawTransaction=async()=>{throw new Error('timeout');};await settleLaunchAlliance(f);let statuses=0;f.connection.getSignatureStatus=async()=>{statuses++;return {value:null};};f.connection.getBlockHeight=async c=>{assert.equal(c,'finalized');return 99;};await settleLaunchAlliance(f);assert.equal(f.prepares,1);f.connection.getBlockHeight=async()=>101;await settleLaunchAlliance(f);assert.equal(f.prepares,2);assert.equal(statuses,3);});
test('no available fees creates no transaction and does not fabricate a receipt',async()=>{const f=fixture();f.prepare=async()=>null;const r=await settleLaunchAlliance(f);assert.equal(r.status,'ACCUMULATING');assert.equal(f.sends,0);assert.equal(publicAllianceSettlement(r).receiptCount,0);});
