import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const server = fs.readFileSync(new URL("../src/index.js", import.meta.url), "utf8");
const maker = fs.readFileSync(new URL("../web/public/site-maker.html", import.meta.url), "utf8");
const coin = fs.readFileSync(new URL("../web/public/coin-site.html", import.meta.url), "utf8");
const dashboard = fs.readFileSync(new URL("../web/public/partner-rewards.html", import.meta.url), "utf8");
const cashCow = fs.readFileSync(new URL("../web/public/cashcow.html", import.meta.url), "utf8");
const redirects = fs.readFileSync(new URL("../web/public/_redirects", import.meta.url), "utf8");

test("every trade charges one fixed 0.65% and a valid referral receives 0.15% from that total", () => {
  assert.match(server, /process\.env\.TRADE_FEE_BPS \|\| process\.env\.BUNDLE_FEE_BPS \|\| "65"/);
  assert.match(server, /process\.env\.REFERRAL_FEE_BPS \|\| "15"/);
  assert.match(server, /const cashCowTradeFeeBps = 0/);
  assert.match(server, /const baseTradeFeeBps = bundleFeeBps/);
  assert.match(server, /connectedTradeFeeBps = jupiterReferralAccount \? baseTradeFeeBps : 0/);
  assert.match(server, /calculateTradeFeeLamports\(amountLamports, session\.userId\)/);
  assert.match(server, /const totalFeeBps = CONFIG\.baseTradeFeeBps/);
  assert.doesNotMatch(server, /referralTradeSurchargeBps/);
  const targets = server.slice(server.indexOf("async function referralFeeTargets"), server.indexOf("function referralSolString"));
  assert.match(targets, /splitTradeFeeAllocation/);
  assert.match(targets, /solReferralPayoutTarget/);
  assert.match(targets, /ownerLamports: referralSplit\.ownerAmount/);
  const partnerPolicy = server.slice(server.indexOf("function partnerTradeFeePolicy"), server.indexOf("function partnerTokenKey"));
  assert.match(partnerPolicy, /const totalBps = baseBps/);
  assert.match(partnerPolicy, /surcharge: false/);
  assert.doesNotMatch(partnerPolicy, /baseBps \+ rewardBps/);
  assert.match(server, /PARTNER_DEV_SHARE_BPS = 5_000/);
  assert.match(server, /PARTNER_HOLDER_SHARE_BPS = 5_000/);
});

test("Solana fee collection preserves a landed platform fee and legacy frozen reward legs", () => {
  const start = server.indexOf("async function collectSolFee");
  const end = server.indexOf("const PARTNER_REWARD_OWNER", start);
  assert.ok(start >= 0 && end > start, "collectSolFee source is missing");
  const fee = server.slice(start, end);
  const ownerStart = fee.indexOf("const ownerTx = addSolFeeMemo(new Transaction()");
  const ownerSend = fee.indexOf("ownerSignature = await sendLegacyTransaction(ownerTx");
  const cashCowStart = fee.indexOf("let cashCowSignature");
  const cashCowPreflight = fee.indexOf("await assertDestinationCanReceiveSol(new PublicKey(targets.cashCowWallet)");
  const cashCowSend = fee.indexOf("cashCowSignature = await sendLegacyTransaction(cashCowTx");
  const referralStart = fee.indexOf("const referralSplits");
  const referralSend = fee.indexOf("referralSignature = await sendLegacyTransaction(referralTx");

  assert.ok(ownerStart >= 0 && ownerSend > ownerStart, "platform fee must have its own transaction");
  assert.ok(cashCowStart > ownerSend, "CashCow work must begin only after the platform send lands");
  assert.ok(cashCowPreflight > cashCowStart && cashCowSend > cashCowPreflight, "CashCow must pass rent preflight before its isolated send");
  assert.ok(referralStart > cashCowSend && referralSend > referralStart, "referrals must use a third, isolated transaction");

  const ownerBlock = fee.slice(fee.indexOf("if (!options.skipOwner"), cashCowStart);
  const cashCowBlock = fee.slice(cashCowStart, referralStart);
  const referralBlock = fee.slice(referralStart);
  assert.match(ownerBlock, /trade_fee_platform_paid/);
  assert.match(ownerBlock, /trade_fee_platform_failed[\s\S]*throw error/);
  assert.match(cashCowBlock, /trade_fee_cashcow_pending/);
  assert.doesNotMatch(cashCowBlock, /trade_fee_cashcow_pending[\s\S]*throw error/);
  assert.ok(cashCowBlock.indexOf("sendLegacyTransaction(cashCowTx") < cashCowBlock.indexOf("recordPartnerRewardFee("), "CashCow rewards must be recorded only after payment lands");
  assert.match(referralBlock, /trade_fee_referral_pending/);
  assert.match(referralBlock, /trade_fee_referral_failed/);
  assert.doesNotMatch(referralBlock, /trade_fee_referral_failed[\s\S]*throw error/);
  assert.match(fee, /sourceSignature/);
  assert.match(fee, /return ownerSignature \|\| cashCowSignature \|\| referralSignature \|\| null/);
});

test("Cash Cow keeps its historical ledger but receives no allocation from new trades", () => {
  assert.match(server, /CASH_COW_RH_TOKEN = "0x4ad72e468e38ec204c605f2e058d61e4d79e2ceb"/);
  assert.match(server, /CASH_COW_REWARD_BPS = CONFIG\.cashCowTradeFeeBps/);
  const ensure = server.slice(server.indexOf("async function ensureCashCowRewardsProgram"), server.indexOf("async function partnerProgramByToken"));
  assert.match(ensure, /holderShareBps: 10_000/);
  assert.match(ensure, /developerShareBps: 0/);
  assert.match(ensure, /mode: "historical"/);
  assert.match(ensure, /baseBps: CONFIG\.baseTradeFeeBps/);
  assert.match(ensure, /rewardBps: CASH_COW_REWARD_BPS/);
  assert.match(ensure, /maxRecipients: 100/);
  const holders = server.slice(server.indexOf("async function rhHolderRewardRecipients"), server.indexOf("async function distributeSolHolderRewards"));
  assert.match(holders, /next_page_params/);
  assert.match(holders, /while \(items\.length < 150\)/);
  assert.match(holders, /address_hash\?\.hash/);
  assert.match(holders, /r\.proxyType === "eip7702"/);
  assert.match(holders, /0\{36\}dead/);
  assert.match(holders, /rhBackfillHolderHistory/);
  assert.match(holders, /slice\(0, 100\)/);
  const history = server.slice(server.indexOf("async function rhHolderContinuousSince"), server.indexOf("async function rhHolderRewardRecipients"));
  assert.match(history, /addresses\/\$\{wallet\}\/token-transfers/);
  assert.match(history, /url\.searchParams\.set\("token", tokenAddress\)/);
  assert.match(history, /historyBackfilledAt/);
  const snapshot = server.slice(server.indexOf("async function snapshotPartnerProgram"), server.indexOf("async function bridgePartnerRhRewards"));
  assert.match(snapshot, /partner_holder_snapshot_failed/);
  assert.match(snapshot, /backfillHistory: program\.token\?\.chain === "robinhood"/);
  assert.doesNotMatch(snapshot, /rhHolderRewardRecipients\([^;]+\.catch\(\(\) => \[\]\)/);
  assert.match(server, /PARTNER_HOLDER_ELIGIBILITY_VERSION = 2/);
  const tradeStart = server.indexOf("async function webRhTradeCore");
  const tradeEnd = server.indexOf("function scheduleRhFeeSweep", tradeStart);
  const trade = server.slice(tradeStart, tradeEnd);
  assert.match(trade, /const feeBps = BigInt\(CONFIG\.baseTradeFeeBps\)/);
  assert.doesNotMatch(trade, /ensureCashCowRewardsProgram/);
  assert.doesNotMatch(trade, /CONFIG\.baseTradeFeeBps \+ \(referralTarget/);
  assert.match(trade, /splitTradeFeeAllocation/);
  assert.match(trade, /const ownerWei = feeSplit\.ownerAmount/);
  assert.ok(trade.indexOf("partnerFeeTxHash = await rhTransferEth") < trade.indexOf("feeTxHash = await rhTransferEth"));
  assert.match(server, /await ensureCashCowRewardsProgram\(\);[\s\S]{0,160}const programs/);
  assert.match(server, /program\.feePolicy\?\.mode !== "historical"/);
  const distribute = server.slice(server.indexOf("async function distributeRhHolderRewards"), server.indexOf("let holderRewardsAutoClaimBusy"));
  assert.match(distribute, /const paidRecipients = \[\]/);
  assert.match(distribute, /paidRecipients\.push\(\{ wallet: p\.wallet, wei: p\.value\.toString\(\), signature: txHash \}\)/);
  assert.match(distribute, /recipients: paidRecipients/);
  assert.match(dashboard, /holder allocation stays inside the displayed total/);
  assert.match(server, /serveStaticHtmlPage\(response, "cashcow\.html"/);
  assert.doesNotMatch(redirects, /\/cashcow\s+\/cashcow\.html\s+200/);
  assert.match(cashCow, /THE FIRST CTO ON ROBINHOOD CHAIN/);
  assert.doesNotMatch(cashCow, /0\.50%|0\.15%|0\.65%/);
  assert.match(cashCow, /CONFIRMED HOLDER PAYOUTS/);
  assert.doesNotMatch(cashCow, /Every Cash Cow trade on SlimeWire grows automatic rewards/);
  assert.match(cashCow, /id="rewardCounter"/);
  assert.match(cashCow, /\/api\/partner-rewards\/CASHCOW/);
  assert.match(cashCow, /CHECK EARNINGS/);
  assert.match(cashCow, /cashcow-rewards-hero\.webp/);
  assert.match(cashCow, /cashcow-holders-meme\.webp/);
  assert.match(cashCow, /cashcow-first-cto-meme\.webp/);
});

test("coin-aware fee plumbing covers Telegram, managed-wallet, bundle, and RH trades", () => {
  assert.match(server, /session\.userId, tokenMint: session\.data\.tokenMint/);
  assert.match(server, /options\.userId, tokenMint, chain: "solana"/);
  assert.match(server, /b\.userId, tokenMint: mint, chain: "solana"/);
  assert.match(server, /recordPartnerRhFee/);
  assert.match(server, /partner\?\.vaultRhWallet/);
});

test("holder policy is daily, snapshot-gated, sqrt-weighted, capped, and bounded to 100", () => {
  assert.match(server, /PARTNER_SNAPSHOT_MS = 6 \* 60 \* 60 \* 1000/);
  assert.match(server, /PARTNER_SETTLEMENT_MS = 24 \* 60 \* 60 \* 1000/);
  assert.match(server, /minHoldHours: 24/);
  assert.match(server, /minSnapshots: 2/);
  assert.match(server, /weighting: "sqrt_balance"/);
  assert.match(server, /maxWalletPoolPct: 5/);
  assert.match(server, /maxRecipients: 100/);
});

test("Site Maker, coin sites, Telegram, and public receipts expose the partner program", () => {
  assert.match(maker, /Community Rewards payout wallet/);
  assert.match(maker, /partnerPayoutWallet/);
  assert.match(maker, /Community Rewards automatically enabled/);
  assert.match(maker, /p\.partner\.enabled = Boolean\(p\.partner\.payoutWallet\)/);
  assert.match(coin, /COMMUNITY REWARDS/);
  assert.match(coin, /LIVE HOLDER REWARDS GENERATED/);
  assert.doesNotMatch(coin, /Every SlimeWire trade keeps the same 0\.50% total fee/);
  assert.match(coin, /\/rewards\/\$\{encodeURIComponent\(p\.partner\.code\)\}/);
  assert.match(dashboard, /PUBLIC HOLDER PROOF/);
  assert.match(dashboard, /MY HOLDER REWARDS/);
  assert.doesNotMatch(dashboard, /Developer paid/);
  assert.match(maker, /PRIVATE DEVELOPER VIEW/);
  assert.match(server, /partnerHolderPublic\(program, store, wallet\)/);
  assert.match(server, /payoutSummary: \{ batches: holderReceipts\.length, transfers: payoutTransfers, transactions: payoutTransactions, uniqueWallets: paidWallets\.size \}/);
  assert.match(server, /paidAmount: format\(paid\), payoutCount/);
  assert.match(server, /partnerProgramAdminForProject\(project\)/);
  assert.match(server, /\/api\/partner-rewards\//);
  assert.match(server, /partner_\$\{program\.code\}/);
  assert.match(redirects, /\/rewards\/\*\s+\/partner-rewards\.html\s+200/);
  assert.match(redirects, /\/ca\/\*\s+\/coin-site\.html\s+200/);
  assert.match(cashCow, /CONFIRMED HOLDER PAYOUTS/);
  assert.match(cashCow, /No new rewards accrue from current trades/);
  assert.doesNotMatch(cashCow, /Pending legacy reward/);
});
